### ISSUE TITLE
dis is warning

### ISSUE THREAD

**Issue by ghost** [berlinfirewall/sichan#1]
![image](https://user-images.githubusercontent.com/29431213/50576354-3304f180-0e08-11e9-9fc0-5a558929289d.png)

solbe ur sqli or we ll hack u -- :{{Ddd AYYILDIZ DİM FEDORA CELAL

**Comment by berlinfirewall** [comment]
were you actually able to do sql injections because i replace the ' with the HTML code for apostrophe in all posts

**Comment by ghost** [comment]
acc i didn't tried to submit when i posted this but it writes "file is an image - png mime" and dies? also u should use `mysqli_real_escape_string` too. (sorry for my autism)
![image](https://user-images.githubusercontent.com/29431213/50592889-f380e880-0e8d-11e9-9684-83764e064754.png)
